#specify a item that can capture mobs
#leave name blank if you want that every 'item' can capture mobs with a specific name
name: 'Catcher'
lore: ['This item can be used to capture animals']

#mobs that can be captured
mobs:
  ['bat',
   'bee',
   'blaze',
   'cat',
   'cave spider',
   'chicken',
   'cod',
   'cow',
   'creeper',
   'dolphin',
   'donkey',
   'drowned',
   'elder guardian',
   'enderman',
   'endermite',
   'evoker',
   'fox',
   'ghast',
   'guardian',
   'horse',
   'husk',
   'llama',
   'magma cube',
   'mooshroom',
   'mule',
   'ocelot',
   'panda',
   'parrot',
   'phantom',
   'pig',
   'pillager',
   'polar bear',
   'pufferfish',
   'rabbit',
   'ravager',
   'salmon',
   'sheep',
   'shulker',
   'silverfish',
   'skeleton',
   'skeleton horse',
   'slime',
   'spider',
   'squid',
   'stray',
   'tropical fish',
   'turtle',
   'vex',
   'villager',
   'vindicator',
   'wandering trader',
   'wither skeleton',
   'wolf',
   'zombie',
   'zombie pigman',
   'zombie villager']